### ISSUE TITLE
DesktopStreamer: hostname set by Servus can't be used to connect

### ISSUE THREAD

**Issue by rdumusc** [BlueBrain/Deflect#54]
On my mac running a DisplayCluster instance, Servus sets the hostname to:
Raphael’s MacBook Air (2)
Which gives a connection error. It should set an IP address or valid hostname instead.

**Comment by eile** [comment]
Then set a valid hostname (SharingPref->Computer Name). :P

`hostname` in a terminal does give you the same?

That's the zeroconf name, and is normally resolvable on any other Mac as is. Of course on the EPFL wifi it seems that .local is not in the search list:

```
[shichi Lunchbox master]% ping shichi
ping: cannot resolve shichi: Unknown host
[shichi Lunchbox master]% ping shichi.local
PING shichi.local (128.179.189.170): 56 data bytes
64 bytes from 128.179.189.170: icmp_seq=0 ttl=64 time=0.058 ms
```

I'm not sure how to move forward with this. It tries to set a valid hostname using `gethostname`, but since name resolval is so gloriously broken here that never works.

I'm not sure that finding an IP address is easier and more robust. Ideas?

**Comment by rdumusc** [comment]
No no, hostname in terminal gives bluebrain077.epfl.ch, which works. I suspect it's just a change in the GUI which is needed to do the mapping, hopefully not in Servus itself.
